rails/config/routes.rb
require 'api_constraints'

Sweep::Application.routes.draw do

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  
  get "password" => "password_resets#index"
  
  # get '/department_validation#index', to: 'department_validation#create'

	namespace :api, :defaults => {:format => 'json'} do
    # Make sure default one is last in the list!
		scope :module => :v2, :constraints => ApiConstraints.new(:version => 2) do
			resources :events
			resources :scans do
        collection do
          post 'registration'
        end
      end
      resources :users
      resources :customers
      resources :departments
      resources :department_validation
      # resources :user_registration
      get 'department_validation/create', to: 'department_validation#index'
		end
		scope :module => :v1, :constraints => ApiConstraints.new(:version => 1, :default => true) do
			resources :events
			resources :scans
      resources :customers
      resources :departments
      resources :department_validation
      get 'department_validation/create', to: 'department_validation#index'
		end
	end
		
  resources :welcome
  resources :profile
  resources :dashboard
  resources :confirm_email
  resources :events, only: [:index, :show, :new, :create]
	#resources :scans, :only =>[:create]
  resources :customers, only: [:new, :create]
  resources :departments, only: [:index, :show, :create, :new]
  #resources :department_validation
  resources :advisors, only: [:create, :new, :destroy]
  resources :admin
  resources :accounts
  resources :password_resets
  resources :users
  resources :sessions
  root :to => 'dashboard#index'
end

rails/app/models/department.rb
class Department < ActiveRecord::Base
  has_many :events
  attr_accessible :customer_id, :name, :valid_key
  after_initialize :init
  validates :customer_id, :presence => true
  validates :name, :uniqueness => {:scope => :customer_id}
  validates :valid_key, :uniqueness => {:scope => :customer_id}
  validates_associated :events
  
  def self.validate_key(key)
    department = find_by_valid_key(key)
    if department
      department
    else
      nil
    end
  end
  
  private
    def init
      self.valid_key ||= SecureRandom.hex(5)
    end

end

rails/app/controllers/api/v1/departments_controller.rb
module Api
  module V1
    class DepartmentsController < SecureApplicationController      
      respond_to :json
      
      def index
        @department = Department.all
        respond_with(:api, @department)
      end
      
      def show
        @department = Department.find(params[:id])
        respond_with(:api, @department)
      end
      
      def create
        @department = Department.create(params[:department])
        respond_with(:api, @department)
      end
      
      def update
        @department = Department.update(params[:id], params[:department])
        respond_with(:api, @department)
      end
      
      def destroy
        @department = Department.destroy(params[:id])
        respond_with(:api, @department)
      end
      
    end
  end
end

rails/app/controllers/api/v2/departments_controller.rb
module Api
  module V2
    class DepartmentsController < SecureApplicationController      
      respond_to :json
      
      def index
        @department = Department.all
        respond_with(:api, @department)
      end
      
      def show
        @department = Department.find(params[:id])
        respond_with(:api, @department)
      end
      
      def create
        @department = Department.create(params[:department])
        respond_with(:api, @department)
      end
      
      def update
        @department = Department.update(params[:id], params[:department])
        respond_with(:api, @department)
      end
      
      def destroy
        @department = Department.destroy(params[:id])
        respond_with(:api, @department)
      end
      
    end
  end
end

rails/app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  
  before_filter :require_login
  
  # GET /departments
  # GET /departments.json
  def index
    @departments = Department.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @departments }
    end
  end

  # GET /departments/1
  # GET /departments/1.json
  def show
    @department = Department.find(params[:id])
    @advisors = Advisor.find_all_by_user_id(current_user[:id])
    @good_user = 0
    if @advisors.count > 0
      @advisors.each do |a|
        if a.department_id == @department.id
          if a.user_id == current_user.id
            @good_user = 1
          end
        end
      end
    else
      redirect_to root_path
      return
    end
    
    if @good_user == 0
      redirect_to root_path
      return
    end
    
    @events = Event.find(:all, order: "starts_at DESC", :conditions => ["department_id = ?", @department.id], :limit => 20)
    @scans = Scan.where("event_id IN (?)", @events.map(&:id))

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @department }
    end
  end

  # GET /departments/new
  # GET /departments/new.json
  def new
    @department = Department.new
    @customers = Customer.all
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @department }
    end
  end

  # GET /departments/1/edit
  def edit
    @department = Department.find(params[:id])
  end

  # POST /departments
  # POST /departments.json
  def create
    @department = Department.new(params[:department])
    @department[:customer_id] = current_user[:customer_id]
    respond_to do |format|
      if @department.save
        format.html { redirect_to controller: "admin", action: "index" }
        format.json { render :json => @department, :status => :created, :location => @department }
      else
        format.html { render :action => "new" }
        format.json { render :json => @department.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /departments/1
  # PUT /departments/1.json
  def update
    @department = Department.find(params[:id])

    respond_to do |format|
      if @department.update_attributes(params[:department])
        format.html { redirect_to @department, :notice => 'Department was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @department.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /departments/1
  # DELETE /departments/1.json
  def destroy
    @department = Department.find(params[:id])
    @department.destroy

    respond_to do |format|
      format.html { redirect_to departments_url }
      format.json { head :no_content }
    end
  end
end

rails/app/helpers/departments_helper.rb
module DepartmentsHelper
end

rails/app/views/departments/_form.html.erb
<%= form_for(@department) do |f| %>
  <% if @department.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@department.errors.count, "error") %> prohibited this department from being saved:</h2>

      <ul>
      <% @department.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!-- <div class="field">
 	 <%= f.collection_select(:customer_id, @customers, :id, :name, {prompt: "Select a Customer"}) %> <br />
  </div> -->
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :valid_key %><br />
    <%= f.text_field :valid_key %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rails/app/views/departments/new.html.erb
<div class="page-fold">
	<div class="row">
		<div class="centered">
			<section>
			<h1>New department</h1>

			<%= render 'form' %>

			<%= link_to 'Back', admin_index_path %>
			</section>
		</div>
	</div>
</div>

rails/app/views/departments/show.html.erb
<div class="page-fold">
	<div class="row">
		<div class="centered">
			<section>
				<h1><%= @department.name %></h1>
			</section>
			<section class="sw-table">
				<div>
				  Download:
				  <%= link_to "Excel", accounts_path(format: "xls", department_id: @department.id  ) %>
				</div>
				 <%= link_to "Create Event", new_event_path %>
				<table border="1">
				<tr>
				<th>Event Title</th>
				<th>Total Attendees</th>
				<th>Unique Attendees</th>
				<th>Event Date</th>
				</tr>
				<% @events.each do |e| %>
					<tr>
					<td><%= link_to e.name, controller: "events", action: "show", id: e.id %></td>
					<% event_scans = @scans.select{ |s| s.event_id == e.id } %>
	
					<td><%= event_scans.size %></td>
					<td><%= event_scans.uniq{ |es| es.value }.size %></td>
					<td><%= l e.starts_at, :format => :short %></td>
					</tr>
			   	 <% end %>
				</table>
			</section>
		</div>
	</div>
</div>