rails/config/routes.rb
require 'api_constraints'

Sweep::Application.routes.draw do

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  
  get "password" => "password_resets#index"
  
  # get '/department_validation#index', to: 'department_validation#create'

	namespace :api, :defaults => {:format => 'json'} do
    # Make sure default one is last in the list!
		scope :module => :v2, :constraints => ApiConstraints.new(:version => 2) do
			resources :events
			resources :scans do
        collection do
          post 'registration'
        end
      end
      resources :users
      resources :customers
      resources :departments
      resources :department_validation
      # resources :user_registration
      get 'department_validation/create', to: 'department_validation#index'
		end
		scope :module => :v1, :constraints => ApiConstraints.new(:version => 1, :default => true) do
			resources :events
			resources :scans
      resources :customers
      resources :departments
      resources :department_validation
      get 'department_validation/create', to: 'department_validation#index'
		end
	end
		
  resources :welcome
  resources :profile
  resources :dashboard
  resources :confirm_email
  resources :events, only: [:index, :show, :new, :create]
	#resources :scans, :only =>[:create]
  resources :customers, only: [:new, :create]
  resources :departments, only: [:index, :show, :create, :new]
  #resources :department_validation
  resources :advisors, only: [:create, :new, :destroy]
  resources :admin
  resources :accounts
  resources :password_resets
  resources :users
  resources :sessions
  root :to => 'dashboard#index'
end

rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link href='https://fonts.googleapis.com/css?family=Raleway:400,700' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=PT+Sans+Narrow' rel='stylesheet' type='text/css'>  
  <title>Sweep</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" >
  <meta name="description" content="Sweep is a tracking and analytics platform for universities and colleges to better understand student engagement on campus.  Sweep captures and displays valuable information about a campus, which can be viewed in a simple and easy to use interface in real time.  Goodbye training." >
  <meta http-equiv="content-type" content="text/html;charset=UTF-8">
  <meta name="keywords" content="Student Engagement, Student Affairs, Campus Life, Clubs and Organizations, iOS, Mobile, Sweep, Kanzu LLC">
  <meta name = "format-detection" content = "telephone=no">
	
  <!-- Google Analytics Tracking -->
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-42852918-2', 'sweepevents.com');
    ga('send', 'pageview');

  </script>
  <!-- End of Google Analytics Tracking -->
  
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= stylesheet_link_tag "https://ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/themes/smoothness/jquery-ui.css" %>
  <%= javascript_include_tag "jquery", "odometer.min", params[:controller] %>
  <%= javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/jquery-ui.min.js" %>
  <%= csrf_meta_tags %>
  
  <!-- <script src="odometer.min.js"></script> -->
  <!-- <script src="http://d3js.org/d3.v3.min.js" charset="utf-8"></script> -->
  
</head>
<body>
	<header>
		<div class="align-left" id="left_header">
			<h1>
				<a href="<%= root_url %>">
					<img src="/assets/logo_kanzu_small.png" id="full-logo" alt="Sweep Kanzu LLC Logo"/>
				</a>
			</h1>
		</div>
		<!-- End of Left Header -->
		<div class="align-right" id="right-header">
				<% if current_user || current_department %>
				<div class="bold inline">
					<% if current_user %>
						<%= link_to current_user.first_name, controller: "profile", action: "index" %> 
					<% elsif current_department %>
						<%= current_department.name %> 
					<% end %>
				</div>
				<div id="user_nav" class="inline">
					|
					<% if current_user %>
					
						<% if current_user.administrator == true || current_user.administrator == 1 %>
							<%= link_to "Admin", controller: "admin", action: "index" %>
							|
						<% end %>
						<%= link_to "Change Password", password_path %>
						|
					<% end %>
					<%= link_to "Log out", log_out_path%>
					
				<% else %>
					<!-- <%= link_to "Sign up", sign_up_path %> -->
					<!-- | -->
					<%= link_to "Log in", log_in_path %>
				<% end %>
				</div>
		</div>
		<!-- End of Right Header -->
	</header>
	<div class="wrapper">
		<!-- <ul> 
			<li><a href="<%= root_url %>">Dash</a></li>
			<li><a href="#departments">Departments</a></li>
			<li><a href="#events">Events</a></li>
			<li><a href="#about">About</a></li>
		</ul> Comment Out for Naviation --> 
	<%= yield %>
	<div class="push"></div>
	</div>
	<!-- End of wrapper -->
<div class="page-fold" id="footer">
	<div class="copy right">
		<span>&copy <%= Time.now.year %> Kanzu LLC. All rights reserved.</span>
		<span id="contact-us"><%= mail_to "support@sweepevents.com", "Contact Us", subject: "Support Ticket" %></span>
	</div>
</div>
<!-- End of Footer -->
</body>
</html>