rails/config/routes.rb
require 'api_constraints'

Sweep::Application.routes.draw do

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  
  get "password" => "password_resets#index"
  
  # get '/department_validation#index', to: 'department_validation#create'

	namespace :api, :defaults => {:format => 'json'} do
    # Make sure default one is last in the list!
		scope :module => :v2, :constraints => ApiConstraints.new(:version => 2) do
			resources :events
			resources :scans do
        collection do
          post 'registration'
        end
      end
      resources :users
      resources :customers
      resources :departments
      resources :department_validation
      # resources :user_registration
      get 'department_validation/create', to: 'department_validation#index'
		end
		scope :module => :v1, :constraints => ApiConstraints.new(:version => 1, :default => true) do
			resources :events
			resources :scans
      resources :customers
      resources :departments
      resources :department_validation
      get 'department_validation/create', to: 'department_validation#index'
		end
	end
		
  resources :welcome
  resources :profile
  resources :dashboard
  resources :confirm_email
  resources :events, only: [:index, :show, :new, :create]
	#resources :scans, :only =>[:create]
  resources :customers, only: [:new, :create]
  resources :departments, only: [:index, :show, :create, :new]
  #resources :department_validation
  resources :advisors, only: [:create, :new, :destroy]
  resources :admin
  resources :accounts
  resources :password_resets
  resources :users
  resources :sessions
  root :to => 'dashboard#index'
end

rails/app/models/advisor.rb
class Advisor < ActiveRecord::Base
  attr_accessible :department_id, :user_id
  validates :user_id, presence: true, numericality: { only_integer: true }
  validates :department_id, presence: true, numericality: { only_integer: true }
  validate :validate_user_and_department_id
  
  private
  def validate_user_and_department_id
    if !User.exists?(self.user_id)
      errors.add(:user_id, "is invalid")
    end
    if !Department.exists?(self.department_id)
      errors.add(:department_id, "is invalid")
    end
  end
  
end

rails/app/controllers/advisors_controller.rb
class AdvisorsController < ApplicationController
  
  before_filter :require_login
  
  def new
    @advisor = Advisor.new
    @users = User.find_all_by_customer_id(current_user[:customer_id])
    @departments = Department.find_all_by_customer_id(current_user[:customer_id])
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @advisor }
    end
  end

  # POST /departments
  # POST /departments.json
  def create
    @advisor = Advisor.new(params[:advisor])
    @advisor[:customer_id] = current_user[:customer_id]
    respond_to do |format|
      if @advisor.save
        format.html { redirect_to controller: "admin", action: "index" }
        format.json { render :json => @advisor, :status => :created, :location => @advisor }
      else
        format.html { render :action => "new" }
        format.json { render :json => @advisor.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  # DELETE /departments/1
  # DELETE /departments/1.json
  def destroy
		if current_user.administrator == true
      @advisor = Advisor.find(params[:id])
      @ad_dept = Department.find(@advisor.department_id)
      if current_user.customer_id == @ad_dept.customer_id
        @advisor.destroy
        flash[:notice] = "Successfully removed advisor"
        redirect_to controller: "admin", action: "index"
      else
        flash[:notice] = "You do not have permissions to do that"
        redirect_to controller: "admin", action: "index"
      end
    else
      flash[:notice] = "You do not have permissions to do that"
      redirect_to controller: "admin", action: "index"
    end
  end
  
end

rails/app/helpers/advisors_helper.rb
module AdvisorsHelper
end

rails/app/views/advisors/_form.html.erb
<%= form_for(@advisor) do |f| %>
  <% if @advisor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@advisor.errors.count, "error") %> prohibited this department from being saved:</h2>

      <ul>
      <% @advisor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
 	 <%= f.collection_select(:user_id, @users, :id, :email, {prompt: "Select a User"}) %> <br />
  </div>
  <div class="field">
 	 <%= f.collection_select(:department_id, @departments, :id, :name, {prompt: "Select a Department"}) %> <br />
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rails/app/views/advisors/edit.html.erb
<h1>Editing department</h1>

<%= render 'form' %>

<%= link_to 'Show', @department %> |
<%= link_to 'Back', departments_path %>

rails/app/views/advisors/index.html.erb
<h1>Listing departments</h1>

<table>
  <tr>
    <th>Customer</th>
    <th>Name</th>
    <th>Valid key</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @departments.each do |department| %>
  <tr>
    <td><%= department.customer_id %></td>
    <td><%= department.name %></td>
    <td><%= department.valid_key %></td>
    <td><%= link_to 'Show', department %></td>
    <td><%= link_to 'Edit', edit_department_path(department) %></td>
    <td><%= link_to 'Destroy', department, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Department', new_department_path %>

rails/app/views/advisors/new.html.erb
<div class="page-fold">
	<div class="row">
		<div class="centered">
			<section>
			<h1>New Advisor</h1>

			<%= render 'form' %>

			<%= link_to 'Back', admin_index_path %>
			</section>
		</div>
	</div>
</div>

rails/app/views/advisors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User ID:</b>
  <%= @advisor.customer_id %>
</p>

<p>
  <b>Name:</b>
  <%= @advisor.name %>
</p>

<p>
  <b>Valid key:</b>
  <%= @advisor.valid_key %>
</p>


<%= link_to 'Edit', edit_department_path(@department) %> |
<%= link_to 'Back', departments_path %>